### ISSUE TITLE
Fix receive data queue memory leak

### ISSUE THREAD

**Issue by cjam** [cjam/gr-flex#1]
Flex Radio sends all of the data via UDP.  This data is surfaced in their API as an event handler which is currently being listened to in the FlexSource python block.  Since we don't know when GNU Radio will call the work function, we place the items on the queue and pull them off the queue when GNU Radio asks for more samples.  This leads to a memory leak since the data being produced by UDP is being delivered faster than GNU radio is pulling it.

**Comment by cjam** [comment]
Just need to pull this into master and we're golden

**Comment by nsbruce** [comment]
This should be closed, closing.
