### ISSUE TITLE
Produce Complex IQ instead of interleaved Float

### ISSUE THREAD

**Issue by cjam** [cjam/gr-flex#5]
It would be good if instead of producing a stream of floats that we then have to de-interleave, we just produce the stream of complex IQ samples.  This should hopefully be fairly straightforward and just be a matter of de-interleaving within the module itself.

**Comment by nsbruce** [comment]
https://stackoverflow.com/questions/5658047/whats-the-fastest-way-to-convert-an-interleaved-numpy-integer-array-to-complex6

**Comment by cjam** [comment]
Interesting.. you know.. thinking of it.. I think there is an output signal type of *complex* instead of *float*.. in which case I'm not sure we'd have to do anything.

**Comment by nsbruce** [comment]
I'm working on it a bit now. I'm having troubles testing from my system but I'm curious whether you do as well or if it's still config issues on my end. Tomorrow if your stuff is installed it would be good to do a quick test.

**Comment by cjam** [comment]
Sounds good, hopefully the pipe to the internet is back to its former glory tomorrow.
